# Generated by Django 6.0.7 on 2026-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pssaword',
            field=models.CharField(default='password123', max_length=255),
            preserve_default=False,
        ),
    ]
