# Generated by Django 6.0.7 on 2026-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pssaword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pssaword',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=255),
            preserve_default=False,
        ),
    ]
